// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/business/v1/business.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 回复评价请求
type ReplyReviewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewID      int64                  `protobuf:"varint,1,opt,name=reviewID,proto3" json:"reviewID,omitempty"`  // 评价ID
	StoreID       int64                  `protobuf:"varint,2,opt,name=storeID,proto3" json:"storeID,omitempty"`    // 商家ID
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`     // 回复内容
	PicInfo       string                 `protobuf:"bytes,4,opt,name=picInfo,proto3" json:"picInfo,omitempty"`     // 回复图片
	VideoInfo     string                 `protobuf:"bytes,5,opt,name=videoInfo,proto3" json:"videoInfo,omitempty"` // 回复视频
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyReviewReq) Reset() {
	*x = ReplyReviewReq{}
	mi := &file_api_business_v1_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyReviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyReviewReq) ProtoMessage() {}

func (x *ReplyReviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_business_v1_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyReviewReq.ProtoReflect.Descriptor instead.
func (*ReplyReviewReq) Descriptor() ([]byte, []int) {
	return file_api_business_v1_business_proto_rawDescGZIP(), []int{0}
}

func (x *ReplyReviewReq) GetReviewID() int64 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *ReplyReviewReq) GetStoreID() int64 {
	if x != nil {
		return x.StoreID
	}
	return 0
}

func (x *ReplyReviewReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyReviewReq) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *ReplyReviewReq) GetVideoInfo() string {
	if x != nil {
		return x.VideoInfo
	}
	return ""
}

// 回复评价响应
type ReplyReviewRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyID       int64                  `protobuf:"varint,1,opt,name=replyID,proto3" json:"replyID,omitempty"` // 回复评价ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyReviewRsp) Reset() {
	*x = ReplyReviewRsp{}
	mi := &file_api_business_v1_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyReviewRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyReviewRsp) ProtoMessage() {}

func (x *ReplyReviewRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_business_v1_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyReviewRsp.ProtoReflect.Descriptor instead.
func (*ReplyReviewRsp) Descriptor() ([]byte, []int) {
	return file_api_business_v1_business_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyReviewRsp) GetReplyID() int64 {
	if x != nil {
		return x.ReplyID
	}
	return 0
}

// AppealReviewRequest 申诉评价的请求参数
type AppealReviewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewID      int64                  `protobuf:"varint,1,opt,name=reviewID,proto3" json:"reviewID,omitempty"`
	StoreID       int64                  `protobuf:"varint,2,opt,name=storeID,proto3" json:"storeID,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	PicInfo       string                 `protobuf:"bytes,5,opt,name=picInfo,proto3" json:"picInfo,omitempty"`
	VideoInfo     string                 `protobuf:"bytes,6,opt,name=videoInfo,proto3" json:"videoInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppealReviewReq) Reset() {
	*x = AppealReviewReq{}
	mi := &file_api_business_v1_business_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppealReviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppealReviewReq) ProtoMessage() {}

func (x *AppealReviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_business_v1_business_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppealReviewReq.ProtoReflect.Descriptor instead.
func (*AppealReviewReq) Descriptor() ([]byte, []int) {
	return file_api_business_v1_business_proto_rawDescGZIP(), []int{2}
}

func (x *AppealReviewReq) GetReviewID() int64 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *AppealReviewReq) GetStoreID() int64 {
	if x != nil {
		return x.StoreID
	}
	return 0
}

func (x *AppealReviewReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AppealReviewReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AppealReviewReq) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *AppealReviewReq) GetVideoInfo() string {
	if x != nil {
		return x.VideoInfo
	}
	return ""
}

type AppealReviewRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppealID      int64                  `protobuf:"varint,1,opt,name=appealID,proto3" json:"appealID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppealReviewRsp) Reset() {
	*x = AppealReviewRsp{}
	mi := &file_api_business_v1_business_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppealReviewRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppealReviewRsp) ProtoMessage() {}

func (x *AppealReviewRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_business_v1_business_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppealReviewRsp.ProtoReflect.Descriptor instead.
func (*AppealReviewRsp) Descriptor() ([]byte, []int) {
	return file_api_business_v1_business_proto_rawDescGZIP(), []int{3}
}

func (x *AppealReviewRsp) GetAppealID() int64 {
	if x != nil {
		return x.AppealID
	}
	return 0
}

var File_api_business_v1_business_proto protoreflect.FileDescriptor

const file_api_business_v1_business_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/business/v1/business.proto\x12\x0fapi.business.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xb6\x01\n" +
	"\x0eReplyReviewReq\x12#\n" +
	"\breviewID\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewID\x12!\n" +
	"\astoreID\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\astoreID\x12$\n" +
	"\acontent\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\xff\x01R\acontent\x12\x18\n" +
	"\apicInfo\x18\x04 \x01(\tR\apicInfo\x12\x1c\n" +
	"\tvideoInfo\x18\x05 \x01(\tR\tvideoInfo\"*\n" +
	"\x0eReplyReviewRsp\x12\x18\n" +
	"\areplyID\x18\x01 \x01(\x03R\areplyID\"\xdb\x01\n" +
	"\x0fAppealReviewReq\x12#\n" +
	"\breviewID\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewID\x12!\n" +
	"\astoreID\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\astoreID\x12\"\n" +
	"\x06reason\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\xc8\x01R\x06reason\x12$\n" +
	"\acontent\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\xc8\x01R\acontent\x12\x18\n" +
	"\apicInfo\x18\x05 \x01(\tR\apicInfo\x12\x1c\n" +
	"\tvideoInfo\x18\x06 \x01(\tR\tvideoInfo\"-\n" +
	"\x0fAppealReviewRsp\x12\x1a\n" +
	"\bappealID\x18\x01 \x01(\x03R\bappealID2\xec\x01\n" +
	"\bBusiness\x12m\n" +
	"\vReplyReview\x12\x1f.api.business.v1.ReplyReviewReq\x1a\x1f.api.business.v1.ReplyReviewRsp\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11b/v1/review/reply\x12q\n" +
	"\fAppealReview\x12 .api.business.v1.AppealReviewReq\x1a .api.business.v1.AppealReviewRsp\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12b/v1/review/appealBC\n" +
	"\x0fapi.business.v1P\x01Z.github.com/yygqzzk/review-b/api/business/v1;v1b\x06proto3"

var (
	file_api_business_v1_business_proto_rawDescOnce sync.Once
	file_api_business_v1_business_proto_rawDescData []byte
)

func file_api_business_v1_business_proto_rawDescGZIP() []byte {
	file_api_business_v1_business_proto_rawDescOnce.Do(func() {
		file_api_business_v1_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_business_v1_business_proto_rawDesc), len(file_api_business_v1_business_proto_rawDesc)))
	})
	return file_api_business_v1_business_proto_rawDescData
}

var file_api_business_v1_business_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_business_v1_business_proto_goTypes = []any{
	(*ReplyReviewReq)(nil),  // 0: api.business.v1.ReplyReviewReq
	(*ReplyReviewRsp)(nil),  // 1: api.business.v1.ReplyReviewRsp
	(*AppealReviewReq)(nil), // 2: api.business.v1.AppealReviewReq
	(*AppealReviewRsp)(nil), // 3: api.business.v1.AppealReviewRsp
}
var file_api_business_v1_business_proto_depIdxs = []int32{
	0, // 0: api.business.v1.Business.ReplyReview:input_type -> api.business.v1.ReplyReviewReq
	2, // 1: api.business.v1.Business.AppealReview:input_type -> api.business.v1.AppealReviewReq
	1, // 2: api.business.v1.Business.ReplyReview:output_type -> api.business.v1.ReplyReviewRsp
	3, // 3: api.business.v1.Business.AppealReview:output_type -> api.business.v1.AppealReviewRsp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_business_v1_business_proto_init() }
func file_api_business_v1_business_proto_init() {
	if File_api_business_v1_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_business_v1_business_proto_rawDesc), len(file_api_business_v1_business_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_business_v1_business_proto_goTypes,
		DependencyIndexes: file_api_business_v1_business_proto_depIdxs,
		MessageInfos:      file_api_business_v1_business_proto_msgTypes,
	}.Build()
	File_api_business_v1_business_proto = out.File
	file_api_business_v1_business_proto_goTypes = nil
	file_api_business_v1_business_proto_depIdxs = nil
}
