// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: business/v1/business.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 回复评价请求
type ReplyReviewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=reviewId,proto3" json:"reviewId,omitempty"`  // 评价ID
	StoreId       int64                  `protobuf:"varint,2,opt,name=storeId,proto3" json:"storeId,omitempty"`    // 商家ID
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`     // 回复内容
	PicInfo       string                 `protobuf:"bytes,4,opt,name=picInfo,proto3" json:"picInfo,omitempty"`     // 回复图片
	VideoInfo     string                 `protobuf:"bytes,5,opt,name=videoInfo,proto3" json:"videoInfo,omitempty"` // 回复视频
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyReviewReq) Reset() {
	*x = ReplyReviewReq{}
	mi := &file_business_v1_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyReviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyReviewReq) ProtoMessage() {}

func (x *ReplyReviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyReviewReq.ProtoReflect.Descriptor instead.
func (*ReplyReviewReq) Descriptor() ([]byte, []int) {
	return file_business_v1_business_proto_rawDescGZIP(), []int{0}
}

func (x *ReplyReviewReq) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *ReplyReviewReq) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *ReplyReviewReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyReviewReq) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *ReplyReviewReq) GetVideoInfo() string {
	if x != nil {
		return x.VideoInfo
	}
	return ""
}

// 回复评价响应
type ReplyReviewRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"` // 回复评价ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyReviewRsp) Reset() {
	*x = ReplyReviewRsp{}
	mi := &file_business_v1_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyReviewRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyReviewRsp) ProtoMessage() {}

func (x *ReplyReviewRsp) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyReviewRsp.ProtoReflect.Descriptor instead.
func (*ReplyReviewRsp) Descriptor() ([]byte, []int) {
	return file_business_v1_business_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyReviewRsp) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

var File_business_v1_business_proto protoreflect.FileDescriptor

const file_business_v1_business_proto_rawDesc = "" +
	"\n" +
	"\x1abusiness/v1/business.proto\x12\x0fapi.business.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xb6\x01\n" +
	"\x0eReplyReviewReq\x12#\n" +
	"\breviewId\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewId\x12!\n" +
	"\astoreId\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\astoreId\x12$\n" +
	"\acontent\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\xff\x01R\acontent\x12\x18\n" +
	"\apicInfo\x18\x04 \x01(\tR\apicInfo\x12\x1c\n" +
	"\tvideoInfo\x18\x05 \x01(\tR\tvideoInfo\"*\n" +
	"\x0eReplyReviewRsp\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x03R\areplyId2\x80\x01\n" +
	"\bBusiness\x12t\n" +
	"\vReplyReview\x12\x1f.api.business.v1.ReplyReviewReq\x1a\x1f.api.business.v1.ReplyReviewRsp\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18business/v1/review/replyBC\n" +
	"\x0fapi.business.v1P\x01Z.github.com/yygqzzk/review-b/api/business/v1;v1b\x06proto3"

var (
	file_business_v1_business_proto_rawDescOnce sync.Once
	file_business_v1_business_proto_rawDescData []byte
)

func file_business_v1_business_proto_rawDescGZIP() []byte {
	file_business_v1_business_proto_rawDescOnce.Do(func() {
		file_business_v1_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_business_v1_business_proto_rawDesc), len(file_business_v1_business_proto_rawDesc)))
	})
	return file_business_v1_business_proto_rawDescData
}

var file_business_v1_business_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_business_v1_business_proto_goTypes = []any{
	(*ReplyReviewReq)(nil), // 0: api.business.v1.ReplyReviewReq
	(*ReplyReviewRsp)(nil), // 1: api.business.v1.ReplyReviewRsp
}
var file_business_v1_business_proto_depIdxs = []int32{
	0, // 0: api.business.v1.Business.ReplyReview:input_type -> api.business.v1.ReplyReviewReq
	1, // 1: api.business.v1.Business.ReplyReview:output_type -> api.business.v1.ReplyReviewRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_business_v1_business_proto_init() }
func file_business_v1_business_proto_init() {
	if File_business_v1_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_business_v1_business_proto_rawDesc), len(file_business_v1_business_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_business_v1_business_proto_goTypes,
		DependencyIndexes: file_business_v1_business_proto_depIdxs,
		MessageInfos:      file_business_v1_business_proto_msgTypes,
	}.Build()
	File_business_v1_business_proto = out.File
	file_business_v1_business_proto_goTypes = nil
	file_business_v1_business_proto_depIdxs = nil
}
