// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: operation/v1/opertation.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditReviewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewID      int64                  `protobuf:"varint,1,opt,name=reviewID,proto3" json:"reviewID,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	OpUser        string                 `protobuf:"bytes,3,opt,name=opUser,proto3" json:"opUser,omitempty"`
	OpReason      string                 `protobuf:"bytes,4,opt,name=opReason,proto3" json:"opReason,omitempty"`
	OpRemarks     *string                `protobuf:"bytes,5,opt,name=opRemarks,proto3,oneof" json:"opRemarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditReviewReq) Reset() {
	*x = AuditReviewReq{}
	mi := &file_operation_v1_opertation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditReviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditReviewReq) ProtoMessage() {}

func (x *AuditReviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_operation_v1_opertation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditReviewReq.ProtoReflect.Descriptor instead.
func (*AuditReviewReq) Descriptor() ([]byte, []int) {
	return file_operation_v1_opertation_proto_rawDescGZIP(), []int{0}
}

func (x *AuditReviewReq) GetReviewID() int64 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *AuditReviewReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuditReviewReq) GetOpUser() string {
	if x != nil {
		return x.OpUser
	}
	return ""
}

func (x *AuditReviewReq) GetOpReason() string {
	if x != nil {
		return x.OpReason
	}
	return ""
}

func (x *AuditReviewReq) GetOpRemarks() string {
	if x != nil && x.OpRemarks != nil {
		return *x.OpRemarks
	}
	return ""
}

type AuditReviewRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditReviewRsp) Reset() {
	*x = AuditReviewRsp{}
	mi := &file_operation_v1_opertation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditReviewRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditReviewRsp) ProtoMessage() {}

func (x *AuditReviewRsp) ProtoReflect() protoreflect.Message {
	mi := &file_operation_v1_opertation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditReviewRsp.ProtoReflect.Descriptor instead.
func (*AuditReviewRsp) Descriptor() ([]byte, []int) {
	return file_operation_v1_opertation_proto_rawDescGZIP(), []int{1}
}

type AuditAppealReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppealID      int64                  `protobuf:"varint,1,opt,name=appealID,proto3" json:"appealID,omitempty"`
	ReviewID      int64                  `protobuf:"varint,2,opt,name=reviewID,proto3" json:"reviewID,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	OpUser        string                 `protobuf:"bytes,4,opt,name=opUser,proto3" json:"opUser,omitempty"`
	OpReason      string                 `protobuf:"bytes,5,opt,name=opReason,proto3" json:"opReason,omitempty"`
	OpRemarks     *string                `protobuf:"bytes,6,opt,name=opRemarks,proto3,oneof" json:"opRemarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAppealReq) Reset() {
	*x = AuditAppealReq{}
	mi := &file_operation_v1_opertation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAppealReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAppealReq) ProtoMessage() {}

func (x *AuditAppealReq) ProtoReflect() protoreflect.Message {
	mi := &file_operation_v1_opertation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAppealReq.ProtoReflect.Descriptor instead.
func (*AuditAppealReq) Descriptor() ([]byte, []int) {
	return file_operation_v1_opertation_proto_rawDescGZIP(), []int{2}
}

func (x *AuditAppealReq) GetAppealID() int64 {
	if x != nil {
		return x.AppealID
	}
	return 0
}

func (x *AuditAppealReq) GetReviewID() int64 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *AuditAppealReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuditAppealReq) GetOpUser() string {
	if x != nil {
		return x.OpUser
	}
	return ""
}

func (x *AuditAppealReq) GetOpReason() string {
	if x != nil {
		return x.OpReason
	}
	return ""
}

func (x *AuditAppealReq) GetOpRemarks() string {
	if x != nil && x.OpRemarks != nil {
		return *x.OpRemarks
	}
	return ""
}

// 对申诉进行审核的返回值
type AuditAppealRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAppealRsp) Reset() {
	*x = AuditAppealRsp{}
	mi := &file_operation_v1_opertation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAppealRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAppealRsp) ProtoMessage() {}

func (x *AuditAppealRsp) ProtoReflect() protoreflect.Message {
	mi := &file_operation_v1_opertation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAppealRsp.ProtoReflect.Descriptor instead.
func (*AuditAppealRsp) Descriptor() ([]byte, []int) {
	return file_operation_v1_opertation_proto_rawDescGZIP(), []int{3}
}

var File_operation_v1_opertation_proto protoreflect.FileDescriptor

const file_operation_v1_opertation_proto_rawDesc = "" +
	"\n" +
	"\x1doperation/v1/opertation.proto\x12\x10api.operation.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xcd\x01\n" +
	"\x0eAuditReviewReq\x12#\n" +
	"\breviewID\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewID\x12\x1f\n" +
	"\x06status\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x06status\x12\x1f\n" +
	"\x06opUser\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\x06opUser\x12#\n" +
	"\bopReason\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\bopReason\x12!\n" +
	"\topRemarks\x18\x05 \x01(\tH\x00R\topRemarks\x88\x01\x01B\f\n" +
	"\n" +
	"_opRemarks\"\x10\n" +
	"\x0eAuditReviewRsp\"\xf2\x01\n" +
	"\x0eAuditAppealReq\x12#\n" +
	"\bappealID\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bappealID\x12#\n" +
	"\breviewID\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewID\x12\x1f\n" +
	"\x06status\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x06status\x12\x1f\n" +
	"\x06opUser\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\x06opUser\x12#\n" +
	"\bopReason\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\bopReason\x12!\n" +
	"\topRemarks\x18\x06 \x01(\tH\x00R\topRemarks\x88\x01\x01B\f\n" +
	"\n" +
	"_opRemarks\"\x10\n" +
	"\x0eAuditAppealRsp2\xed\x01\n" +
	"\tOperation\x12o\n" +
	"\vAuditReview\x12 .api.operation.v1.AuditReviewReq\x1a .api.operation.v1.AuditReviewRsp\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11o/v1/review/audit\x12o\n" +
	"\vAuditAppeal\x12 .api.operation.v1.AuditAppealReq\x1a .api.operation.v1.AuditAppealRsp\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11o/v1/appeal/auditB2\n" +
	"\x10api.operation.v1P\x01Z\x1creview-o/api/operation/v1;v1b\x06proto3"

var (
	file_operation_v1_opertation_proto_rawDescOnce sync.Once
	file_operation_v1_opertation_proto_rawDescData []byte
)

func file_operation_v1_opertation_proto_rawDescGZIP() []byte {
	file_operation_v1_opertation_proto_rawDescOnce.Do(func() {
		file_operation_v1_opertation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operation_v1_opertation_proto_rawDesc), len(file_operation_v1_opertation_proto_rawDesc)))
	})
	return file_operation_v1_opertation_proto_rawDescData
}

var file_operation_v1_opertation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_operation_v1_opertation_proto_goTypes = []any{
	(*AuditReviewReq)(nil), // 0: api.operation.v1.AuditReviewReq
	(*AuditReviewRsp)(nil), // 1: api.operation.v1.AuditReviewRsp
	(*AuditAppealReq)(nil), // 2: api.operation.v1.AuditAppealReq
	(*AuditAppealRsp)(nil), // 3: api.operation.v1.AuditAppealRsp
}
var file_operation_v1_opertation_proto_depIdxs = []int32{
	0, // 0: api.operation.v1.Operation.AuditReview:input_type -> api.operation.v1.AuditReviewReq
	2, // 1: api.operation.v1.Operation.AuditAppeal:input_type -> api.operation.v1.AuditAppealReq
	1, // 2: api.operation.v1.Operation.AuditReview:output_type -> api.operation.v1.AuditReviewRsp
	3, // 3: api.operation.v1.Operation.AuditAppeal:output_type -> api.operation.v1.AuditAppealRsp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_operation_v1_opertation_proto_init() }
func file_operation_v1_opertation_proto_init() {
	if File_operation_v1_opertation_proto != nil {
		return
	}
	file_operation_v1_opertation_proto_msgTypes[0].OneofWrappers = []any{}
	file_operation_v1_opertation_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operation_v1_opertation_proto_rawDesc), len(file_operation_v1_opertation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operation_v1_opertation_proto_goTypes,
		DependencyIndexes: file_operation_v1_opertation_proto_depIdxs,
		MessageInfos:      file_operation_v1_opertation_proto_msgTypes,
	}.Build()
	File_operation_v1_opertation_proto = out.File
	file_operation_v1_opertation_proto_goTypes = nil
	file_operation_v1_opertation_proto_depIdxs = nil
}
